# PROJECT STATUSES
PROJECT_STATUS_INITIATED = 1
PROJECT_STATUS_PHASE_1_IMAGE_ANALYZED = 2
PROJECT_STATUS_PHASE_2_JSON_GENERATED = 3
PROJECT_STATUS_PHASE_3_IAC_GENERATED = 4

# JSON FILE STATUSES
JSON_GENERATION_PENDING = 0
JSON_GENERATION_GENERATED = 1

# IAC SCRIPT STATUSES
IAC_GENERATION_PENDING = 0
IAC_GENERATION_GENERATED = 1