# PROJECT STATUSES
PROJECT_STATUS_INITIATED = 1
PROJECT_STATUS_PHASE_1_IMAGE_ANALYSIS_IN_PROGRESS = 2
PROJECT_STATUS_PHASE_2_IMAGE_ANALYZED = 3
PROJECT_STATUS_PHASE_3_JSON_GENERATION_IN_PROGRESS = 4
PROJECT_STATUS_PHASE_4_JSON_GENERATED = 5
PROJECT_STATUS_PHASE_5_IAC_GENERATION_IN_PROGRESS = 6
PROJECT_STATUS_PHASE_6_IAC_GENERATED = 7

# JSON FILE STATUSES
JSON_GENERATION_PENDING = 0
JSON_GENERATION_GENERATED = 1

# IAC SCRIPT STATUSES
IAC_GENERATION_PENDING = 0
IAC_GENERATION_GENERATED = 1